### ISSUE TITLE
Reading sequences error

### ISSUE THREAD

**Issue by leannmlindsey** [quim0/WFA-GPU#5] opened 2023-04-10 22:09 UTC
I tried to run the software with a regular fasta file and this was the error that I got.  it says that the file doesn't exist, but you can see in the line immediately afterward that the file does exist and it is a regular fasta file format.

Can you upload a test file to your github that I can use to test?

Also, since there is only one test file required, does this mean that you are doing an all-to-all alignment test?

(base) [u1323098@notch367:WFA-GPU]$ cd bin/
(base) [u1323098@notch367:bin]$ ./wfa.affine.gpu -i /uufs/chpc.utah.edu/common/home/u1323098/sundar-group-space2/ADEPT/DATA/test-data/dna-query.fasta -o outfile.txt -p -O -g 3,6,1 -x 
INFO: Using CUDA device "NVIDIA RTX A6000" with capability 8.6 (tools/aligner.c:179)
INFO: Penalties: M=0, X=3, O=6, E=1. (tools/aligner.c:216)
INFO: Reading sequences file... (tools/aligner.c:218)
Invalid file format. Could not read pattern in line 1
Error reading file: /uufs/chpc.utah.edu/common/home/u1323098/sundar-group-space2/ADEPT/DATA/test-data/dna-query.fasta (No such file or directory).
(base) [u1323098@notch367:bin]$ head /uufs/chpc.utah.edu/common/home/u1323098/sundar-group-space2/ADEPT/DATA/test-data/dna-query.fasta
>0
CGCCCGATGGCAATCCGGAACTTTCTTCGGCTGCCTGGTATACCGGAGTCGTCATTCTGGTGGCCGAATTATGGTTTACGGGTGAGGCGTTCGTCAAGCGCCAGTCCACCGAGCTTGCCGTGACGTCGAAGCGGATCATAGCGAAATTCG
>1
CGAATTTCGCTATGATCCGCTTCGACGTCACGGCAAGCTCGGTGGACTGGCGCTTGACGAACGCCTCACCCGTAAACCATAATTCGGCCACCAGAATGACGACTCCGGTATACCAGGCAGCCGAAGAAAGTTCCGGATTGCCATCGGGCG
>2
CGAATTTCGCTATGATCCGCTTCGACGTCACGGCAAGCTCGGTGGACTGGCGCTTGACGAACGCCTCACCCGTAAACCATAATTCGGCCACCAGAATGACGACTCCGGTATACCAGGCAGCCGAAGAAAGTTCCGGATTGCCATCGGGCG
>3
GCCATGAAAAGTATCGCCTTGCCAAACACCGTCCAGTGCAGCCTGGCTTTGGCATACAGTTTTTCGCCCTGCATCAGGTTATTTTCGACGTATCCCATCGCCCTGTACTCCGTTTATAGCTTTACTGTTTACCTGAACAATTCTCCTTCC
>4
TTTTGTTTTTTCATCAGGGTTCAGCCTAAATTCCCGAGCATTTATAACTATGCCTCGCTCAGACCAAGTATCGGAATGTCGAGTGCCTTGAGTATCTGCCGCTGGGAAGAAGTTCCGGGACGTTGTTCCGTTGCCACAAATTCTACTGTT

**Comment by quim0** [comment] 2023-04-11 09:03
Hello,

The tool performs pairwise alignment, it gets only one input file because it uses `.seq` files as the original WFA tool. This file format is very simple, a `seq` file has the following format:

```
>query1
<target1
>query2
<target2
>query3
<target3
```

Then, the tool would align `query1` with `target1`, `query2` with `target2`... etc

Here is a oneliner that you can use to transform your `fasta` files (`query.fasta` and `target,fasta`) to `seq`: 

``` bash
paste <(cat query.fasta | paste - -) <(cat target.fasta | paste - -) | awk '{print(">"$2"\n<"$4)}' > sequences.seq
```

Then, you can use the `sequences.seq` file as input for the tool.

The `No such file or directory` is not the correct error here, I'll improve the error reporting in this case, thanks for the feedback.
I'll also upload some examples and clarify the file format on the repo, if you need anything else let me know.

**Comment by leannmlindsey** [comment] 2023-04-11 17:46
Oh Thank you very much for your response.  That makes sense, I just hadn't used your other tool WFA.

**Comment by quim0** [comment] 2023-04-20 09:05
I close the issue as it seems that the problem is solved, if you need anything else let me know

**Closed as completed by quim0** 2023-04-20 09:05 UTC
